import Head from "next/head";
import Cal, { getCalApi } from "@calcom/embed-react";
import { useEffect } from "react";
import { FaLinkedin } from "react-icons/fa";
import { HiOutlineMail } from "react-icons/hi";

export default function Home() {
  useEffect(() => {
    (async function () {
      const cal: any = await getCalApi();
      cal("ui", {
        styles: { branding: { brandColor: "#06b6d4" } },
        hideEventTypeDetails: false,
      });
    })();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col justify-center items-center gap-14 w-full h-full mt-10 md:mt-16 px-5">
        <div className="flex flex-col md:flex-row justify-center items-center gap-8">
          <img
            alt="profile picture"
            src="/chris.jpeg"
            className="rounded-full w-32 h-32 outline-1 outline-cyan-500 outline"
          />
          <div className="flex flex-col gap-4">
            <h1 className="text-3xl font-medium md:text-4xl text-slate-200">
              Chris Cooper
            </h1>
            <div className="flex flex-col gap-1.5">
              <p className="font-extralight text-slate-100">
                Hey, I&apos;m Chris 👋
              </p>
              <p className="font-extralight text-slate-100">
                I&apos;m a Software Developer, primarily focussed on the
                front-end.
              </p>
              <p className="font-extralight text-slate-100">
                Book in a call with me today!
              </p>
              <div className="flex flex-row gap-2">
                <a href="https://www.linkedin.com/in/chris--cooper/">
                  <FaLinkedin color="#0077b5" size={28} />
                </a>
                <a href="mailto:christopher.cooper@mail.com">
                  <HiOutlineMail color="whitesmoke" size={30} />
                </a>
              </div>
            </div>
          </div>
        </div>
        <Cal
          calLink={process.env.CALLINK ?? ""}
          style={{ width: "100%", height: "100%", overflow: "hidden" }}
        />
      </main>
    </>
  );
}
